### ISSUE TITLE
mapscript not available for python 3

### ISSUE THREAD

**Issue by raffscallion** [pnwairfire/bluesky#1]
I was able to get bspipe installed and running on my ubuntu 16.04 AWS virtual machine.

I ran into errors when trying to execute `bsp -i fire_fuels.json consumption`

ERROR: Missing dependencies required for ecoregion lookup - No module named 'mapscript'

Checking in python, I see that I had installed mapscript for python 2.7, but not 3.5.  Further digging revealed that mapscript does not appear to be compatible with python 3 yet. [https://github.com/mapserver/mapserver/pull/5290](url)

I wanted to see how you handled this before attempting to build something using my limited linux skills.

**Comment by jdubowy** [comment]
Thanks for pointing it it out.  It's actually a known issue.  When I upgraded the bluesky package to python 3.5, it broke ecoregion lookup.  (I should probably migrate all todos and issues, which I currently track in trello, to github.) For now, you can specify a default ecoregion (e.g. 'western'), which is used when lookup fails.

**Comment by raffscallion** [comment]
OK, thanks.  For now I can do my own lookup and provide the ecoregion as input.

**Comment by jdubowy** [comment]
I've removed the dependency on mapscript in ecoregion lookup.  The code now uses the [fiona](https://pypi.python.org/pypi/Fiona/1.7.2) and [shapely](https://pypi.python.org/pypi/Shapely) packages instead.  I haven't yet merged the branch containing this change, since I'd like to first try to speed it up, but I should be merging soon.

**Comment by jdubowy** [comment]
ecoregion lookup works in v2.3.1.  It supports two implementations - one that uses fiona and shapely, and the other that uses the python ogr binding.  Using ogr is much faster and is the default, but I left the shapely+fiona implementation in for now.

**Comment by raffscallion** [comment]
Cool.  I'll test it out and let you know how it goes.
-Sean

**Comment by jdubowy** [comment]
I've published a new docker image, v2.3.1, as well.  It's listed on https://hub.docker.com/r/pnwairfire/bluesky/tags/.
