### ISSUE TITLE
Input file for Bluesky runs with just lat/lons "specified points"

### ISSUE THREAD

**Issue by ggrodzinsky** [pnwairfire/bluesky#217]
I have noticed examples which include perimeter/polygons for input json files. I just have area and lat/lon point locations where the point is the center of the fire area. It says you can provide an input file with just "specified points" with lat/lon, area, county, etc. I have successfully run it with someone else's inputs that used polygons so I know the system I have installed works. 
Is there an example anyone can provide that is an input json file for bluesky that only has "specified points" (no polygon or perimeter, I don't have that information) for multiple fires? I wanted to see the format. When I ran it with just the lat/lon, county, state, start, end for two sample fire lat/lon locations and asked for more values.

Thanks for your time!

I have provided a sample text file (so it can load here) to show you what I did. My apologies if I overlooked something obvious as I am really new at this.

[ca_rx_test5.txt](https://github.com/pnwairfire/bluesky/files/6640265/ca_rx_test5.txt)

Gil

**Comment by ggrodzinsky** [comment]
To clarify: I have included a png file with the input file on the left and code on the right with the error and the input json file on the left (what you would get if opened the txt file in my previous inquiry. 
![Screenshot (1524)](https://user-images.githubusercontent.com/83603778/121731064-762a1b00-cabe-11eb-9651-32d204e5e7af.png)

**Comment by jdubowy** [comment]
Your failure is due to the fact that  your input file is invalid JSON.  You have a trailing comma at line 35 column 15 (char 819).

For an example with specified points instead of polygon, take a look at https://github.com/pnwairfire/bluesky/blob/master/docs/examples.md.

**Comment by ggrodzinsky** [comment]
Thanks Joel: I removed the comma and still get the ValueERROR(self.MISSING_LOCATION_INFO_MSG), but other issue went away.
You stated that there is an example under https://github.com/pnwairfire/bluesky/blob/master/docs/examples.md.
I looked and only see an example that has specified points and perimeter/polygon. I thought according to the notes I had that you can run it with specified points OR perimeter/polygon.
Do I need a perimeter like in the example provided? There is "one contributor" so could not find another example.

Thanks so much for the quick response!!

Gil

**Comment by jdubowy** [comment]
If both perimeter polygon and specified points are defined, the perimeter polygon is ignored. So you can just remove the polygon, which would give you:

```
{
    "fires": [
        {
            "id": "SF11C14225236095807750",
            "event_of" :{
                "name": "Natural Fire near Snoqualmie Pass, WA",
                "id": "SF11E826544"
            },
            "activity": [
                {
                    "name": "First day",
                    "active_areas": [
                        {
                            "start": "2015-08-04T17:00:00",
                            "end": "2015-08-05T17:00:00",
                            "utc_offset": "-09:00",
                            "country": "USA",
                            "state": "WA",
                            "ecoregion": "western",
                            "specified_points": [
                                {
                                    "name": "HMW-32434",
                                    "lat": 47.41,
                                    "lng": -121.41,
                                    "area": 120
                                },
                                {
                                    "lat": 47.42,
                                    "lng": -121.43,
                                    "area": 103,
                                    "ecoregion": "western"
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}
``` 

The problem with your input is that you defined everything under the specified point objects. You need to move `start`, `end`, etc. up a level to the active area object.  Look in the example for what fields need to be specified in the active area object vs. the specified points objects.

**Comment by jdubowy** [comment]
Because your specified points have different end times, you'll need to separate them out into two active areas.  Also, I noticed that you used `"specified points"` rather than `"specified_points"` (i.e. you have a space instead of an underscore).

I'll get your example working and will paste the correct input data here once I do.

**Comment by ggrodzinsky** [comment]
Success! It was the underscore! And subtropical was wrong. I guess I need to use eastern. I used western just since I knew that worked before.

Gil

**Comment by ggrodzinsky** [comment]
Oh I did it for one lat/lon to eliminate that possibility of error. Oh okay, you can still send me the successful input file for multiple lat/lons.

Thanks for being so helpful and sorry for overlooking commas/underscores!

From: Grodzinsky, Gil
Sent: Friday, June 11, 2021 4:09 PM
To: pnwairfire/bluesky ***@***.***>; pnwairfire/bluesky ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [pnwairfire/bluesky] Input file for Bluesky runs with just lat/lons "specified points" (#217)

Success! It was the underscore! And subtropical was wrong. I guess I need to use eastern. I used western just since I knew that worked before.

Gil

**Comment by jdubowy** [comment]
Glad you got it working. Sorry for the delay - I got pulled off by other projects.

Here's your input data structured correctly:

```
{
  "fires": [
    {
      "activity": [
        {
          "active_areas": [
            {
              "ecoregion": "subtropical",
              "start": "2020-01-03 11:00:00",
              "end": "2020-01-03 14:30:00",
              "utc_offset": "-4:00",
              "country": "USA",
              "state": "GA",
              "county": "13055",
              "specified_points": [
                {
                  "lat": 34.502,
                  "lng":-85.275,
                  "area": 111
                }
               ]
            },
            {
              "ecoregion": "subtropical",
              "start": "2020-01-03 11:00:00",
              "end": "2020-01-03 16:30:00",
              "utc_offset": "-4:00",
              "country": "USA",
              "state": "GA",
              "county": "13295",
              "specified_points": [
                {
                  "lat": 34.596,
                  "lng":-85.166,
                  "area": 273
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}
```

As for ecoregion, the supported values (which are used in consume) are 'western', 'boreal', and 'southern'.
