### ISSUE TITLE
Fuelmoisture model error

### ISSUE THREAD

**Issue by Porkking** [pnwairfire/bluesky#260]
Hi Joel,

I just noticed that a wonderful fuelmoisture model is available in BlueSKY. I try to use it for a case while I receive an error warning:

2022-06-18 02:38:14,404 ERROR: Failed to compute fuel moisture for loc 26.711, -81.038 using model <bluesky.fuelmoisture.nfdrs.NfdrsFuelMoisture object at 0x7fb37229ff70>: 'float' object is not subscriptable

Do you know why it happens?
[config.txt](https://github.com/pnwairfire/bluesky/files/8932840/config.txt)
[SE2015_01_02.txt](https://github.com/pnwairfire/bluesky/files/8932841/SE2015_01_02.txt)

Thanks,
Zongrun

**Comment by jdubowy** [comment]
Thanks for the bsp command and log output.  Unfortunately, no stack trace is logged (I should have checked the code). Could I have access to your met file so that I can repro the failure?  If not, could you modify the code to log the stack trace?

**Comment by Porkking** [comment]
I could share my meteorology data. I download it via NOAA website. NOAA provides ARL data and I used NAM 12 km product. The data I used is for 2015-01-02. I can share it via google drive:
https://drive.google.com/file/d/1l6sF568HETFUu8uql6EKDDmDkYZk4MK9/view?usp=sharing
If there are anything I can help, please let me know.

**Comment by jdubowy** [comment]
Thanks for the met.  I ran your example locally without error, which makes it difficult to help you.  What version of bluesky are you running?

**Comment by jdubowy** [comment]
You can try, but there aren't any code changes between 4.3.48 and 4.3.50 that should make a difference with this fuelmoisture error.

To get a stack trace, rerun with `config` > `fuelmoisture` > `skip_failures` set to false, and then look for the error in the output json file.

**Comment by Porkking** [comment]
I try to rerun with the configuration. Although I receive the same error message in the log:
```2022-06-18 02:38:14,404 ERROR: Failed to compute fuel moisture for loc 26.711, -81.038 using model <bluesky.fuelmoisture.nfdrs.NfdrsFuelMoisture object at 0x7fb37229ff70>: 'float' object is not subscriptable```
The output is totally fine:
[output.txt](https://github.com/pnwairfire/bluesky/files/8953352/output.txt)

**Comment by jdubowy** [comment]
The stack trace should be in the output fire data, not the log.

**Comment by jdubowy** [comment]
I'm actually able to repro the error.  I missed the log error message in my run.  I'll figure out what's going on later tonight or tomorrow.
