### ISSUE TITLE
SEV plumerise model for multiple fires input

### ISSUE THREAD

**Issue by Porkking** [pnwairfire/bluesky#265]
Hi Joel,
Hope everything goes well recently. The SEV plumerise model for multiple fires input does not return the correct time step for each fire. For example, assume we have two fires:
The first fire starts at 10:00 2021-04-06 and end at 16:00 2021-04-06. The second fire starts at 11:00 2021-04-06 and end at 15:00 2021-04-06. Although these two fires have different start time and end time, the key of plumerise of these two fires are the same: from 2021-04-06T10:00 to 2021-04-06T14:00. 
Notice that if I run these two fires separately, the plumerise time is as expected (2021-04-06T10:00 to 2021-04-06T15:00 for the first fire and 2021-04-06T11:00 to 2021-04-06T14:00 for the second fire). And I just found this problem in SEV model. FEPS results are seem to be correct.
Do you have any ideas for this issue? I can share my input and output data:
https://drive.google.com/drive/folders/1tTY5Uvl-Fp-iTPCk3ZWjvrL5PRtpqMFx?usp=sharing
Thanks,
Zongrun

**Comment by jdubowy** [comment]
Hi Zongrun,  It's a bug, and I've found the problem in the code. Thanks for finding it!  I'll try to get out a fix later today or tomorrow.

**Comment by jdubowy** [comment]
Fixed with 26780bf0a9593cff3a740cbaa36792a49987d189 and included in v4.3.62.
