### ISSUE TITLE
ref_power for SEV model

### ISSUE THREAD

**Issue by zli867** [pnwairfire/bluesky#289]
Hi Joel,

I hope you are doing well recently. I just checked the latest version of BlueSky (v4.5.22). The ref_power in the configuration file does not affect the FRP in the SEV model. From my understanding, the FRP value should be $ref\textunderscore power \times frp$ (unit will be in Watts). However, I tried to run a case with case 1: $frp=10.52, ref\textunderscore power=1 \times 10^6$ and a case 2: $frp=10.52 \times 10^6, ref\textunderscore power=1$ and the results of plume heights are different. The first case shows a plume height of around 300 m, while the latter shows a plume height of around 20,000 m. I can provide the output data for these cases (I think all input and configuration information are also recorded in the file). 
case 1: [FtStwrt2022_03_02_SEV_out_MW.json](https://github.com/user-attachments/files/16367306/FtStwrt2022_03_02_SEV_out_MW.json)
case 2: [FtStwrt2022_03_02_SEV_out_ref_W.json](https://github.com/user-attachments/files/16367346/FtStwrt2022_03_02_SEV_out_ref_W.json)
Do you have any ideas on why this happened? Please let me know if you also want all input files.

Thanks,
Zongrun

**Comment by jdubowy** [comment]
Hi Zongrun,

Our implementation of SEV, which admittedly is pretty old, does not match your understanding of how it's suppose to work.  You can see how `ref_power` comes into play here:

https://github.com/pnwairfire/plumerise/blob/master/plumerise/sev.py#L106-L108

It could very well be that we need to update our SEV implementation.

**Comment by zli867** [comment]
Hi Joel,

Sorry for the late response. I am now back to the project related to SEV. It is more clear to read the source code. It seems the code assumed the FRP unit is Watts. Also, when there is no FRP data, the [code](https://github.com/pnwairfire/plumerise/blob/e53b77eeb2767c2bb16a6be07b32511f3848c730/plumerise/sev.py#L52C13-L52C37) uses following formula:
```
frp = 4180.8 * fire_area
```
I believe the area unit is acres in the formula. The FRP should also be in the Watts unit.

Thanks for reminding me of the meaning of `ref_power`. I misunderstood it before. I checked the [paper](https://acp.copernicus.org/articles/12/1995/2012/) again. The ref_power meaning should be $P_{f0}$, and the paper used $10^6$. The FRP is in the Watts unit in the paper. From my understanding, if the user uses mega-Watts FRP as input, the $P_{f0}$ should be 1.

It would be great to add a line on the FRP unit in [README](https://github.com/pnwairfire/bluesky/blob/master/docs/data-units.md). I think the current default value is Watts.

Thanks,
Zongrun

**Comment by jdubowy** [comment]
Thanks Zongrun. I'll update the data units doc include FRP.

**Comment by jdubowy** [comment]
We've decided that bluesky should expect FRP in Megawatts, but SEV should continue to work with Watts . So I've updated the SEV wrapper code in bluesky to convert Megawatts to Watts: https://github.com/pnwairfire/bluesky/commit/aa272bf65a0a3e8b0a3045b56706d7f4bb17535a
