### ISSUE TITLE
refactor data structure

### ISSUE THREAD

**Issue by jdubowy** [pnwairfire/bluesky#91]
#### the main two ways the code needs to be updated:

 - [x] update code to iterate through extra layer of collections
 - [ ] update code to work with selected_points or perimeter_polygon

#### itemized tasks list:

 - [x] remove ingestion module, unit tests, and all references to it
 - [x] update Fire class (and unit tests) to work with new structure
 - [x] update FiresManager class (and unit tests)
 - [x] update filtering and merging code, and unit tests
 - [x] remove splitactivity module?
 - [x] delete [origin/]joel/mergegrowth-module branch (local and remote)
 - [x] update all modules in bluesky.modules
   - [x] filter
   - [x] merge
   - [x] fuelbeds
   - [x] consumption
   - [x] emissions
   - [x] timeprofiling
   - [x] findmetdata
   - [x] localmet
   - [x] plumerising
   - [x] dispersion
   - [x] export
   - [x] extrafiles
   - [x] visualization
   - [x] load
 - [x] update everything under bluesky.dispersers
 - [x] update everything under bluesky.extrafilewriters
 - [x] update everything under bluesky.visualizers
 - [x] update everything under bluesky.loaders -- update sf2 and firespider loaders to produce new data structure
 - [x] update tests
   - [x] unit tests
   - [x] regression tests
     - [x] consumption_emissions
     - [x] modules
 - [x] update dev scripts
 - [x] any other code updates
 - [x] update docs
 - [x] rename plumerising module as plumerise
 - [x] rename timeprofiling module as timeprofile
 - [x] update ad hoc test data
 - [x] ad hoc test filtering and merging
 - [x] ad hoc test fuelbeds through vsmoke and export
 - [x] ad hoc test fuelbeds through hysplit visualization and export
 - [x] create and publish v4.1.0

#### Not sure about:

 - [ ] rename fire 'meta' field as 'properties' ***<- not going to do***

## New structure (from google doc):

```
fires [ // list of fires
     { // fire
        name
        other metadata associated with fire

        perimeter_polygon

        summary of fire calcuations {
            total size (across all days)
            total fuels available to burn
            total fuel consumed
            total GHG emissions ?
            total PM2.5 emissions
        }

        activity [ // array of specific collections of areas
             {  //collection of areas
                name of collection (can be anything, often used for "day")
                active_areas [
                    area {  // polygon with embedded points
                        time span
                        perimeter polygon { }
                        specified points [
                            point {
                                ID or name
                                lat
                                lon
                                area
                                assigned fuelbeds [list]
                                consumption calcs [ by hour ]
                                emissions calcs [ by hour ]
                                time profile [ by hour ]
                                plume rise [[ by hour / vertical layer ]]
                            }
                            point {
                                same as above
                            }
                        ]
                        summary of area calcs {
                            total size (across all days)
                            total fuels available to burn
                            total fuel consumed
                            total GHG emissions ?
                            total PM2.5 emissions
                        }
                    }

                    area {  // polygon only no embedded points
                        time span
                        perimeter polygon { }
                        no specified points
                        area
                        assigned fuelbeds {list}
                        consumption calcs { by hour }
                        emissions calcs { by hour }
                        time profile { by hour }
                        plume rise {by hour / vertical layer? }
                    }

                    area {  // point only
                        time span
                        specified point {
                            ID or name
                            lat
                            lon
                            area
                            assigned fuelbeds {list}
                            consumption calcs { by hour }
                            emissions calcs { by hour }
                            time profile { by hour }
                            plume rise {by hour / vertical layer? }
                        }
                    }

                summary of area collection {
                    total size (across all days)
                    total fuels available to burn
                    total fuel consumed
                    total GHG emissions ?
                    total PM2.5 emissions
            } // end collection of areas

            collection 2 {
            }
        } end activity

```

## Notes on logic

 - use selected_points, if defined, to determine fuelbeds, compute consumption, etc.; else fall back on perimeter;
 - area assigned to perimeter is burned area, not necessarily the actual area of the perimeter  ***(<-- so we sould  *not* use area returned by fuelbeds look up if it's already defined)***

**Comment by smitimittal** [comment]
Hi! Wanted to check in and see if Bluesky has been updated yet to allow for fuelbed calculations with just a perimeter specified and no 'specified_points.' If not, is there a standard way/a script that lets you generate a list of specified_points with some density within a polygon, given its perimeter coordinates?

**Comment by jdubowy** [comment]
I must have accidentally missed checking that one item. perimeter polygons have been supported since this issue was closed.   Here's an example:

```
echo '{
        "fires": [
            {
                "activity": [
                    {
                        "active_areas": [
                            {
                                "start": "2021-09-26T00:00:00",
                                "end": "2019-09-27T00:00:00",
                                "utc_offset": "-07:00",
                                "perimeter": {
                                    "polygon": [
                                        [-121.4522115, 47.4316976],
                                        [-121.3990506, 47.4316976],
                                        [-121.3990506, 47.4099293],
                                        [-121.4522115, 47.4099293],
                                        [-121.4522115, 47.4316976]
                                    ]
                                }
                            }
                        ]
                    }
                ]
            }
        ]
}' > fire-w-perim.json
docker run --rm -ti \
    -v $PWD/:/bluesky/ \
    -w /bluesky/ \
    -e PYTHONPATH=/bluesky/ \
    -e PATH=/bluesky/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    bluesky \
    ./bin/bsp --log-level=DEBUG --indent 4 -o consume-out.json \
    -i fire-w-perim.json \
    ecoregion fuelbeds consumption
```
